info:
  contact: {}
paths:
  /sellers:
    post:
      consumes:
      - application/json
      description: Create a new seller with name, category, and description
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new seller
      tags:
      - sellers
swagger: "2.0"
